In [37]:
import numpy as np
import math

In [44]:
N = 20
kmin = 2
kmax = round(math.sqrt(N))
k = np.random.exponential(size = N).round() + kmin

In [59]:
while ((k > kmax)*1).sum() > 0:
    k = np.delete(k,k > kmax)
    residual = N - len(k)
    kaux = np.random.exponential(size = residual).round() + kmin

C:\Users\Dave Mont\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: in the future insert will treat boolean arrays and array-likes as boolean index instead of casting it to integer
  


In [57]:
np.delete(k,k > kmax)

C:\Users\Dave Mont\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: in the future insert will treat boolean arrays and array-likes as boolean index instead of casting it to integer
  """Entry point for launching an IPython kernel.


array([4., 3., 3., 3., 3., 3., 3., 3., 3., 3., 2., 2., 2., 2., 2., 2., 2.,
       2.])

In [64]:
k = list()
i=0
aux=0
while (i<N):
    aux = np.random.exponential(scale=1.0, size= 1).round()+ kmin
    if ( aux < np.sqrt(N)):
        k.append(aux)
        i = i+1
k = np.asarray(k).flatten()
k[::-1].sort()

In [72]:
listas = []

for i in k:
    listas.append(np.zeros(round(i.item())))

In [106]:
for i in range(N):
    j = i + 1
    for j

0
[array([0., 0., 0.]), array([1., 1., 1.]), array([2., 2., 2.]), array([3., 3., 3.]), array([4., 4., 4.]), array([5., 5., 5.]), array([6., 6., 6.]), array([7., 7., 7.]), array([8., 8.]), array([9., 9.]), array([10., 10.]), array([11., 11.]), array([12., 12.]), array([13., 13.]), array([14., 14.]), array([15., 15.]), array([16., 16.]), array([17., 17.]), array([18., 18.]), array([19., 19.])]
[array([0., 0., 0.]), array([1., 1., 1.]), array([2., 2., 2.]), array([3., 3., 3.]), array([4., 4., 4.]), array([5., 5., 5.]), array([6., 6., 6.]), array([7., 7., 7.]), array([8., 8.]), array([9., 9.]), array([10., 10.]), array([11., 11.]), array([12., 12.]), array([13., 13.]), array([14., 14.]), array([15., 15.]), array([16., 16.]), array([17., 17.]), array([18., 18.]), array([19., 19.])]


KeyboardInterrupt: 

In [97]:
 listas

[array([0., 0., 0.]),
 array([1., 1., 1.]),
 array([2., 2., 2.]),
 array([3., 3., 3.]),
 array([4., 4., 4.]),
 array([5., 5., 5.]),
 array([6., 6., 6.]),
 array([7., 7., 7.]),
 array([8., 8.]),
 array([9., 9.]),
 array([10., 10.]),
 array([11., 11.]),
 array([12., 12.]),
 array([13., 13.]),
 array([14., 14.]),
 array([15., 15.]),
 array([16., 16.]),
 array([17., 17.]),
 array([18., 18.]),
 array([19., 19.])]

In [84]:
listas[0]

array([0., 0., 0.])